name: Update date and weather info
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  generate-dynamic-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install Dependencies
        run: python -m pip install html2image==2.0.1 requests
      - name: Generate Images
        env:
          WEATHER_API: ${{ secrets.WEATHER_API }}
        run: |
          python update_images.py
      - name: Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff-index --quiet HEAD || (git commit -am "[bot] updated images" --allow-empty && git push -f)
